"""is verified

Revision ID: 1218277d2c3a
Revises: 96aa61e3986d
Create Date: 2025-09-24 10:32:18.591480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1218277d2c3a'
down_revision: Union[str, Sequence[str], None] = '96aa61e3986d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('is_verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'is_verified')
    # ### end Alembic commands ###
