"""verified field

Revision ID: 96aa61e3986d
Revises: 81114c502454
Create Date: 2025-09-24 10:22:24.080132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '96aa61e3986d'
down_revision: Union[str, Sequence[str], None] = '81114c502454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'user_accounts',
        sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false())
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'is_verified')
    # ### end Alembic commands ###
