"""field

Revision ID: ccfcf4e4de4f
Revises: 0bbb8ea8b203
Create Date: 2025-09-24 10:47:16.021088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ccfcf4e4de4f'
down_revision: Union[str, Sequence[str], None] = '0bbb8ea8b203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_accounts', sa.Column('is_verified', sa.BOOLEAN(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_accounts', 'is_verified')
    # ### end Alembic commands ###
